### ISSUE TITLE
Define the standards for 2015 year class

### ISSUE THREAD

**Issue by jhansche** [facebook/device-year-class#13]
Now that 2015 has come to a close, and we are now in 2016, it should be possible to declare the standards necessary for a `YearClass.CLASS_2015` device year classification.

**Comment by SeyelentEco** [comment]
Hi, we're currently working on redefining the current Year Classes in order to make them more accurate and useful.  We'll add a 2015 option if we see that there are phones that perform significantly better than YC2014 phones.  For now you should treat the 2014 Year Class as 2014+, if we find a need to add a 2015 class, it'll be similarly named (2015+).
