### ISSUE TITLE
No devices show up as having a year class after 2014

### ISSUE THREAD

**Issue by LukeStClair** [facebook/device-year-class#14]
Right now, no devices show up as having a year class after 2014 on 1.0.1.

Are there plans to update the classification at regular intervals to reflect new devices being released?

**Comment by SeyelentEco** [comment]
This is on purpose.  Think of the 2014 year class as 2014+.  We haven't found a need to differentiate 2014/2015 devices because they perform about the same.  The year classes help us (and developers) group phones that behave a similarly and share the same performance characteristics.  We're working on refining these classes and fixing some phones that fall into the wrong class but we don't have any plans for a 2015 class at the moment.
